# Generated by Django 5.2.3 on 2025-06-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10)),
                ('tipo_componente', models.CharField(help_text='Tipo de componente (ej: KPI, TABLA, GRAFICO.line)', max_length=50)),
                ('parametros_requeridos', models.JSONField(blank=True, default=dict, help_text='Lista de parámetros que la plantilla espera. Ej: ["provincia_id", "anio"]')),
                ('config_visualizacion', models.JSONField(blank=True, default=dict, help_text='Configuración de visualización por defecto. Ej: {"title": "Título por Defecto"}')),
                ('plantilla_sql', models.TextField(blank=True, null=True)),
                ('plantilla_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente de Informe',
                'verbose_name_plural': 'Componentes de Informes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definición de Informe',
                'verbose_name_plural': 'Definiciones de Informes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InformeComposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('config_override', models.JSONField(blank=True, default=dict, help_text='Sobrescribe la configuración de visualización para este informe. Ej: {"title": "Título Específico"}')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.componente')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.informe')),
            ],
            options={
                'verbose_name': 'Composición de Informe',
                'verbose_name_plural': 'Composiciones de Informes',
                'ordering': ['informe', 'orden'],
                'unique_together': {('informe', 'componente')},
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='componentes',
            field=models.ManyToManyField(related_name='informes', through='ref.InformeComposicion', to='ref.componente'),
        ),
    ]
