# Generated by Django 5.2.3 on 2025-07-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_limpiar_componentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='tipo_grafico',
            field=models.CharField(blank=True, choices=[('line', 'Líneas'), ('bar', 'Barras Verticales'), ('barh', 'Barras Horizontales'), ('scatter', 'Dispersión (Scatter Plot)'), ('histogram', 'Histograma'), ('box', 'Cajas (Box Plot)'), ('pie', 'Torta / Anillo'), ('treemap', 'Mapa de Árbol (Treemap)'), ('sunburst', 'Explosión Solar (Sunburst)'), ('map', 'Mapa Coroplético')], help_text='Especificación del tipo de gráfico (ej: line, barh, pie).', max_length=50),
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo_componente',
            field=models.CharField(choices=[('KPI', 'KPI'), ('GRAFICO', 'Gráfico'), ('TABLA', 'Tabla'), ('TEXTO', 'Texto')], help_text='El tipo general del componente.', max_length=20),
        ),
    ]
