# Generated by Django 5.2.3 on 2025-06-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectopfi',
            old_name='region',
            new_name='region_cofecyt',
        ),
        migrations.RenameField(
            model_name='rrhhract',
            old_name='anio_id',
            new_name='anio',
        ),
        migrations.RenameField(
            model_name='rrhhract',
            old_name='provincia',
            new_name='provincia_id',
        ),
        migrations.AddField(
            model_name='indicadorescontexto',
            name='region_cofecyt',
            field=models.CharField(blank=True, help_text='Región según COFECYT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamientossnn',
            name='sistema_nacional',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exportaciontecnologicadestino',
            name='fob_millones_sum',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exportaciontecnologicadestino',
            name='intensidad_tecnologica',
            field=models.BooleanField(help_text='True si alta, False si es baja'),
        ),
        migrations.AlterField(
            model_name='exportaciontecnologicadestino',
            name='pais_destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exportaciontop5',
            name='gran_rubro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exportaciontop5',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exportaciontop5',
            name='region_cofecyt',
            field=models.CharField(max_length=100),
        ),
    ]
