# Generated by Django 5.2.3 on 2025-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0002_rename_region_proyectopfi_region_cofecyt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='codigo_indec',
            field=models.CharField(blank=True, help_text='Código oficial según INDEC', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region_iso',
            field=models.CharField(blank=True, help_text='Código de provincia según ISO 3166-2:AR', max_length=20, null=True),
        ),
    ]
