# Generated by Django 5.2.3 on 2025-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0003_alter_provincia_codigo_indec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrhhract',
            name='provincia_id',
            field=models.IntegerField(),
        ),
    ]
