# Generated by Django 5.2.3 on 2025-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0004_alter_rrhhract_provincia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
