# Generated by Django 5.2.3 on 2025-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0005_alter_patente_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='lens_id',
            field=models.CharField(help_text='Identificador único de la patente en Lens', max_length=255),
        ),
        migrations.AddField(
            model_name='patente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
