# Generated by Django 5.2.3 on 2025-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0006_patente_id_alter_patente_lens_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patente',
            name='letra_ipc_descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
