# Generated by Django 5.2.3 on 2025-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0007_alter_patente_id_alter_patente_letra_ipc_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='application_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
