# Generated by Django 5.2.3 on 2025-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0008_alter_patente_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto_id',
            field=models.IntegerField(),
        ),

        migrations.AddField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
