# Generated by Django 5.2.3 on 2025-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0009_proyecto_id_alter_proyecto_proyecto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocientifico',
            name='producto_id',
            field=models.IntegerField(),
        ),

        migrations.AddField(
            model_name='productocientifico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
