# Generated by Django 5.2.3 on 2025-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0010_productocientifico_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportaciontecnologicadestino',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exportaciontecnologicadestino',
            name='cod_prov',
            field=models.IntegerField(),
        ),
    ]
