# Generated by Django 5.2.3 on 2025-06-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0011_alter_exportaciontecnologicadestino_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportaciontecnologicadestino',
            name='cod_prov',
        ),
        migrations.AddField(
            model_name='exportaciontecnologicadestino',
            name='provincia',
            field=models.CharField(blank=True, db_column='cod_prov', max_length=100, null=True),
        ),
    ]
