# Generated by Django 5.2.3 on 2025-06-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0012_remove_exportaciontecnologicadestino_cod_prov_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadorescontexto',
            old_name='id',
            new_name='provincia_id',
        ),
        migrations.RenameField(
            model_name='indicadorescontexto',
            old_name='provincia',
            new_name='provincia_nombre',
        ),
    ]
