# Generated by Django 5.2.3 on 2025-07-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0013_rename_id_indicadorescontexto_provincia_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadorescontexto',
            old_name='provincia_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='indicadorescontexto',
            old_name='provincia_nombre',
            new_name='provincia',
        ),
    ]
