# Generated by Django 5.2.3 on 2025-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0014_rename_provincia_id_indicadorescontexto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patente',
            name='es_institucion_nacional',
            field=models.BooleanField(default=False),
        ),
    ]
