# Generated by Django 5.2.3 on 2025-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_fuente', '0015_alter_patente_es_institucion_nacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversionid',
            name='tipo_institucion_ract',
            field=models.CharField(blank=True, help_text='Tipo de institución que invirtió', max_length=100, null=True),
        ),
    ]
